name: Test Musl Build

on:
  workflow_dispatch:

jobs:
  test-musl-setup:
    name: Test musl-tools installation
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [x86_64-unknown-linux-musl, aarch64-unknown-linux-musl]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
          
      - name: Install musl-tools (Linux musl)
        if: contains(matrix.target, 'musl')
        run: |
          sudo apt-get update
          sudo apt-get install -y musl-tools

      - name: Verify musl-tools installation
        run: |
          musl-gcc --version
          ls -la /usr/bin/musl-gcc
          echo "Target: ${{ matrix.target }}"
          rustc --version
          rustc --print target-list | grep musl